import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { logInfo, logWarn } from "./logging.js";

const RENDER_MARKER = '"_renderedBy": "aios-telegram-bridge"';

/**
 * Render `.cursor/mcp.json` from RECALL_API_KEY so cursor-agent inside the
 * bridge process can call RecallSync MCP tools. Skips if a hand-written
 * mcp.json exists (no marker).
 */
export function renderRecallsyncMcp(repoRoot: string): void {
  const apiKey = process.env.RECALL_API_KEY?.trim();
  const url =
    process.env.RECALLSYNC_MCP_URL?.trim() || "https://mcp.recallsync.com/mcp";

  if (!apiKey) {
    logWarn(
      "RECALL_API_KEY missing; skipping .cursor/mcp.json render (RecallSync MCP unavailable)"
    );
    return;
  }

  const dir = join(repoRoot, ".cursor");
  const mcpFile = join(dir, "mcp.json");

  if (existsSync(mcpFile)) {
    const existing = readFileSync(mcpFile, "utf8");
    if (!existing.includes(RENDER_MARKER)) {
      logInfo("Hand-written .cursor/mcp.json found; leaving untouched");
      return;
    }
  }

  const payload = {
    _renderedBy: "aios-telegram-bridge",
    _renderedAt: new Date().toISOString(),
    _comment:
      "Generated by telegram-bridge on start. Source: RECALL_API_KEY in .env.local. Restart bridge after changing the key.",
    mcpServers: {
      "recallsync-primary": {
        url,
        headers: { api_key: apiKey },
      },
    },
  };

  mkdirSync(dir, { recursive: true });
  writeFileSync(mcpFile, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
  logInfo(`Rendered ${mcpFile} for RecallSync MCP`);
}
